In [1]:
import numpy as np

In [4]:
l1 = np.arange(1,16)

In [5]:
l1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
li = np.array(l1,dtype='float')

In [7]:
li

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [10]:
l2 = np.arange(5,8,0.5)
l2

array([5. , 5.5, 6. , 6.5, 7. , 7.5])

In [12]:
#crear m,atriz identidad
iden = np.eye(6)
iden

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [16]:
# re distribuir
l3 = np.zeros((4,5))
l3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
l4 = l3.reshape(5,4)
l4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
cre = np.arange(32)
cre

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [24]:
cre_reshape = cre.reshape(8,4)
cre_reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [26]:
#aplanar vector
l4 = np.array( [[1,2,3],[4,5,6],[7,8,9]])
l4

l5 = np.ravel(l4)
l5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#flatten crea una copia y aplana la matriz
l4.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#transponer
l4.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])