In [1]:
import numpy as np

In [6]:
vectorr = np.arange(25)
vectorr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
#redimensioanr
vectorr=vectorr.reshape(5,5)

In [13]:
## dimensiones?
vectorr.ndim

2

In [15]:
#forma
vectorr.shape

(5, 5)

In [16]:
#peso
vectorr.size

25

In [17]:
#tipo de datos
vectorr.dtype

dtype('int32')

In [20]:
#tamaño d ecada numero en la matriz
vectorr.itemsize

4

In [22]:
##extraer sub matriz
print(vectorr[2:4,1:3])

[[11 12]
 [16 17]]


In [25]:
#condicion
condd = (vectorr >= 12)
condd

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [26]:
# mopstrar resultados condicion
print(vectorr[condd])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
