In [2]:
import numpy as np

In [3]:
## 1- array con datos entre 5 y 120
tarea1 = np.arange(5,120)
print(tarea1)

[  5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76
  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94
  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112
 113 114 115 116 117 118 119]


In [6]:
## 2- crear una matriz 4x4 con los valores de 0 - 15
tarea2 = np.arange(16).reshape(4,4)
tarea2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
## 3- crear la identidad de 7x7
tarea3 = np.eye(7)
tarea3

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [9]:
## 4- Crear un array de 20 elementos y transformarlo en una matriz 5x4
tarea4 = np.arange(20).reshape(5,4)
tarea4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
## 5- crear un array con 20 numeros con los valores entre 0 y 5 espaciados de forma uniforme
tarea5 = np.arange(0,5,0.25)
tarea5

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75])

In [11]:
print(len(tarea5))

20
